version: "3.8"

services:
  nextjs:
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}

    ports:
      - "3000:3000"

    restart: always

    environment:
      NODE_ENV: production