export {default as HomeIcon} from './home.svg';
export { default as Belongings } from "./belongings.svg";
export { default as Connections } from "./connections.svg";
export { default as Dynasty } from "./dynasty.svg";
export { default as Infractions } from "./infractions.svg";
export { default as Invitations } from "./invitations.svg";
export { default as Permissions } from "./permissions.svg";
export { default as Property } from "./property.svg";
export { default as RealEstate } from "./real-estate.svg";
export { default as Reward } from "./reward.svg";
export { default as Structures } from "./structures.svg";
export { default as Transaction } from "./transaction.svg";
export { default as CLoseIcon } from "./close.svg";
export { default as MenuIcon } from "./menu.svg";
export { default as ActiveMenuIcon } from "./darkactiveMenu.svg";
export { default as Language } from "./Language.svg";