export const staticMenuToShow = [
    { name: "home", url: ``, order: "-2" },
    { name: "citizens", url: "citizens", order: "-2" },
    { name: "list of levels", url: "levels/citizen", order: "-2" },
    { name: "property" },
    { name: "real estate" },
    { name: "structures" },
    { name: "belongings" },
    { name: "permissions" },
    { name: "invitations" },
    { name: "transaction" },
    { name: "reward" },
    { name: "dynasty" },
    { name: "connections" },
    { name: "crimes" },
    { name: "news" },
    { name: "articles" },
    { name: "trainings" },
    { name: "about", url: "about", order: "-1" },
    { name: "contact", url: "contact", order: "-1" },
    { name: "version" },
    { name: "calendar" },
    { name: "overview" },
  ];
