name: Deployment
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Self-Hosted Server
        env:
          SSH_PASSWORD: 'mEbmfPpsZABA7bVwv4eJ'
          SSH_HOST: '2.187.100.51'
          SSH_USERNAME: 'frdevelop2'
          REMOTE_DEPLOY_PATH: '/home/frdevelop2/public_html'
          SSH_PORT: 4041
        run: |
          # Set the name of the application
          APP_NAME="frdevelop2"

          # Check if the application is already running
          if sshpass -f ~/.ssh/password ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "pm2 show $APP_NAME &> /dev/null"; then
            # Restart the application
            sshpass -f ~/.ssh/password ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "pm2 restart $APP_NAME"
          else
            # Start the application
            sshpass -f ~/.ssh/password ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "pm2 start npm start --name $APP_NAME"
          fi
